gptfdisk: Add volume_manager to visibility
* Fixup after 1fedcd9d5fd78276bcdd77f87ddba5d83207685c
  We need it for our recovery.

Fix:
error: bootable/recovery/volume_manager/Android.bp:17:1: module "libvolume_manager" variant "android_recovery_arm64_armv8-2a-dotprod_cortex-a76_shared": depends on //external/gptfdisk:libsgdisk which is not visible to this module
You may need to add "//bootable/recovery/volume_manager" to its visibility

Change-Id: I2ddcbe70fd2f65ec0b37fcb236d1adb8a34f5469